### ISSUE TITLE
Issue when posting using email with a dot

### ISSUE THREAD

**Issue by erichirlemann** [Viascom/hipchat-api#13]
Hello,

When posting a private message like:

```
HipChat hipchat = new HipChat(accessToken);
PrivateMessage p = new PrivateMessage();
p.setNotify(true);
p.setMessage_format(MessageFormat.TEXT);
p.setMessage("Hello world");
p.setUserId(email);
hipChat.usersAPI().sendPrivateMessage(p);
```

This works all fine if the email address looks like foo@adomain.org.

But when the email address has a dot, such as `foo.bar@adomain.org`, got an exception:
`Response-Statuscode: 400`
In the exception, one can read `The request JSON can not be parsed as valid JSON: Expecting property enclosed in double quotes`.

Deeper debugging shows the body sent to the hipchat server looks like: `{ .bar@adomain.com", "message":"Hello world","notify":"true","message_format":"text"}`, what is obviously not a valid JSON.

**Comment by itsmefox** [comment]
Hi
There was a bug in the regex statement for the replacement of not needed request fields.
The newest commit https://github.com/Viascom/hipchat-api/commit/9d27c23c6349e06f955062b83c97cdab4b81ff9e9d27c23 should fix this bug.

**Comment by itsmefox** [comment]
The change is available in this SNAPSHOT release on oss.sonatype.org:
[hipchat-api:2.0.2-SNAPSHOT](https://oss.sonatype.org/service/local/repositories/snapshots/content/ch/viascom/hipchat-api/2.0.2-SNAPSHOT/hipchat-api-2.0.2-20160620.102048-1.jar)
