### ISSUE TITLE
Mentions returned from history API is empty

### ISSUE THREAD

**Issue by ppearcy** [Viascom/hipchat-api#15]
Not really shocking:

```
public class MessageMention {
}
```

I may add support for this sooner or later and wanted to get notified if this got fixed.

**Comment by itsmefox** [comment]
This feature will be included in the next release.
Commit 7a8341a includes the updated MessageMention class.

**Comment by nik-sta** [comment]
Hi @ppearcy :)

We've released a new beta version of our hipchat-api. This release includes the solution of your created issue. If something isn't how it should be, don't hesitate to write us. We are happy to see people using our api.

Cheers, Nikola
