### ISSUE TITLE
Release 2.0.3?

### ISSUE THREAD

**Issue by rjimgal** [Viascom/hipchat-api#19]
First of all thank you for all the work you've done here.

Is there any change to release 2.0.3 version? I'm specially interested in the fix applied in https://github.com/Viascom/hipchat-api/pull/18

Thanks in advance,
Rafa.

**Comment by nik-sta** [comment]
Hi @rjimgal! We'll release asap a new version with your improvement and the changes you mentioned in #18. Thanks for supporting us.

**Comment by rjimgal** [comment]
That'd be great, thanks.

**Comment by rjimgal** [comment]
@nikolastankovic any update on this?

**Comment by nik-sta** [comment]
Hi @rjimgal :) We're developing the new version and have improved and updated the whole project. The newest code is in this branch Viascom/hipchat-api/feature/switchToFoxHttp. We'll release this week a release candidate and give you a migration guide. More infos are following asap. It would be great if you can give us a feedback after the migration. Cheers, Nikola

**Comment by nik-sta** [comment]
The release candidate will be "ch.viascom:hipchat-api:2.1-RC1"

**Comment by itsmefox** [comment]
Hi @rjimgal 
The release of the release candidate of version 2.1 will be available in maven central in the next hour. We rewrote the whole logic under the hood and changed to our new http library [FoxHttp](https://github.com/Viascom/FoxHttp).
We would be pleased if you could test the new version and give us some feedback. 
Please note that the API has changed slightly and there is currently no migration guide available.

release candidate version: **2.1-RC1**

**Comment by rjimgal** [comment]
A collage of mine did the refactor for the new version without too much hustle, apart from https://github.com/Viascom/hipchat-api/pull/24

Also, I don't know if this was related to the new version, but we had to add commons io dependency manually.

Apart from that, the new version seems to work good, thanks.

**Comment by nik-sta** [comment]
Hi @rjimgal :)

Thanks for your fantastic help and comments! We've released now the version 2.1-RC2. This should by ready in a couple of minutes and reachable on maven central. This release should fix your issues :)

Cheers, Nikola
